### ISSUE TITLE
Sipxtapi Recording files in PCM format

### ISSUE THREAD

**Issue by GajulaSujay** [sipXtapi/sipXtapi#1]
Hi All,
         Sipxmedialib is currently supporting pcm format for recording which makes the recording files huge. Is there a possibility to record in gsm format. If so please guide me with some process of how to also. As this is my first time with sipxtapi code if anything you guys find funny bear with me.You can reply me back to gajula.sujay@gmail.com.
Working Environment: Windows 7 Enterprise Edition
Sipxtapi-3.2.1

Regards,
G.Sujay.

**Comment by dgpetrie** [comment]
You can record file in GSM/wave as well as Opus/ogg file formats for a more compressed file size.  The recording APIs at the sipXtapi and mediaAdaptor layers have arguments for specifying the encoding.
