### ISSUE TITLE
Is this repo active?

### ISSUE THREAD

**Issue by simone-gaiarin** [sipXtapi/sipXtapi#3]
There are two repository `sipXtapi` and `sipXtapi-svn-mirror`. The latest seems more updated. 
- Which one should be used?
- What is the purpose of the repo `sipXtapi`?

**Comment by dgpetrie** [comment]
sipXtapi is the active repo now.

sipXtapi-svn-mirror was being automatically synchronized with the subversion repo while it was active.  Its contents were merged to the sipXtapi repo..  The svn repo is no longer active.

**Comment by simgunz** [comment]
You can put `sipXtapi-svn-mirror` in archived mode to make it clear that is not active.
